### ISSUE TITLE
STT Vietnamese don't work after update to Core 2023.12.1

### ISSUE THREAD

**Issue by kizovinh** [hugobloem/homeassistant-addons#11]
First I want to thank you for this integration, it works flawlessly for my native language Vietnamese. But after update to Homeassistant Core 2023.12.1, It detected my language and response as English. I rolled back to 2023.12.0 and it worked fine. Do you have any idea about it?

**Comment by hugobloem** [comment]
Hi, thanks for pointing this out. I unfortunately can't test this at the moment. However it seems like there's an update to the underlying Wyoming protocol package that might cause the issue. Will test this soon.

**Comment by kizovinh** [comment]
> Hi, thanks for pointing this out. I unfortunately can't test this at the moment. However it seems like there's an update to the underlying Wyoming protocol package that might cause the issue. Will test this soon.

Thank you so much. I look forward to hear good news

**Comment by saya6k** [comment]
I have same problem. I used STT in Korean, but after update, it interprete my Korean to some sort of English sound similar.

**Comment by hugobloem** [comment]
Hi, apologies for the delay. I have updated the wyoming and azure speech services packages. The updated add-on works with 2023.12.1 now.
