### ISSUE TITLE
Standard docker images

### ISSUE THREAD

**Issue by pwntester** [hugobloem/homeassistant-addons#22]
Hey, thanks for these addons, they work great!

I recently moved from HAOS to the docker and so I lost addons on the way. I got these addons working as standalone docker services with the following services, but I thought that other people could want to do the same and perhaps its better to publish these images with the python entrypoint rather than the HASS supervisor one.

```
  wyoming-microsoft-stt:
    container_name: wyoming-microsoft-stt
    image: "ghcr.io/hugobloem/amd64-wyoming-microsoft-stt:latest"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    entrypoint:
      - /bin/bash
      - -c
      - |
        python3 -m wyoming-microsoft-stt \
          --uri "tcp://0.0.0.0:10300" \
          --subscription-key "${AZURE_SPEECH_KEY}" \
          --service-region "${AZURE_REGION}" \
          --download-dir /data \
          --update-languages \
          --debug
    ports:
      - "10300:10300/tcp"
  wyoming-microsoft-tts:
    container_name: wyoming-microsoft-tts
    image: "ghcr.io/hugobloem/amd64-wyoming-microsoft-tts:latest"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    entrypoint:
      - /bin/bash
      - -c
      - |
        python3 -m wyoming-microsoft-tts \
          --uri "tcp://0.0.0.0:10200" \
          --subscription-key "${AZURE_SPEECH_KEY}" \
          --service-region "${AZURE_REGION}" \
          --download-dir /data \
          --update-voices \
          --debug
    ports:
      - "10200:10200/tcp"
```

**Comment by hugobloem** [comment]
Hi thank you for sharing this. 

I have added Dockerfiles to each of the individual repositories: [wyoming-microsoft-tts](https://github.com/hugobloem/wyoming-microsoft-tts) and [wyoming-microsoft-stt](https://github.com/hugobloem/wyoming-microsoft-stt). When a next version is released these packages should be available from GitHub packages.
