### ISSUE TITLE
Missing "Version" in AsrProgram and AsrModel

### ISSUE THREAD

**Issue by luca-roccia** [hugobloem/homeassistant-addons#30]
Hi,

With last release I get error of missing "version" info in  AsrProgram and AsrModel; I'm on HA 2024.2.1.
Adding a dummy version="1.0.4" it starts to work as expected.

Maybe something changed with last HA release?

**Comment by hugobloem** [comment]
Hi, sorry for the uploading of faulty versions. Version 1.0.6 is tested to be working. The underlying wyoming package had been updated and required a version number even though it was marked as optional.
